import {
  DEFAULT_MODEL_ID as CURATED_DEFAULT_MODEL_ID,
  DEFAULT_MODEL_NAME as CURATED_DEFAULT_MODEL_NAME,
  DEFAULT_TUTOR_MODEL_ID as CURATED_DEFAULT_TUTOR_MODEL_ID,
  DEFAULT_TUTOR_MEMORY_MODEL_ID as CURATED_DEFAULT_TUTOR_MEMORY_MODEL_ID,
} from '@/data/curatedModels';

export const DEFAULT_MODEL_ID = CURATED_DEFAULT_MODEL_ID;
export const DEFAULT_MODEL_NAME = CURATED_DEFAULT_MODEL_NAME;
export const DEFAULT_TUTOR_MODEL_ID = CURATED_DEFAULT_TUTOR_MODEL_ID;
export const DEFAULT_TUTOR_MEMORY_MODEL_ID = CURATED_DEFAULT_TUTOR_MEMORY_MODEL_ID;
export const PINNED_MODEL_ID = DEFAULT_MODEL_ID;

export const DEFAULT_TUTOR_MEMORY_FREQUENCY = 5;

// UI layout constants
export const HEADER_HEIGHT_PX = 56;

// Streaming / UI tuning
export const STREAM_SCROLL_THROTTLE_MS = 160;
export const MAX_FALLBACK_RESULTS = 5;

// Attachments limits
export const MAX_IMAGES_PER_MESSAGE = 4;
export const MAX_PDF_SIZE_MB = 15;
export const MAX_AUDIO_SIZE_MB = 15;
