export const SIDEBAR_WIDTH_PX = 360;
export const SIDEBAR_GESTURE_MARGIN_PX = 40;
export const SIDEBAR_EDGE_PX = 24;
export const SIDEBAR_SWIPE_THRESHOLD_PX = 56;
export const SIDEBAR_SWIPE_HYSTERESIS_PX = 12;

export const SIDEBAR_GESTURE_REGION_PX = SIDEBAR_WIDTH_PX + SIDEBAR_GESTURE_MARGIN_PX;
