'use client';
import type { Message, Chat, ModelDescriptor } from '@/lib/types';
import { computeCost } from '@/lib/cost';
import { formatMetricsForDisplay } from '@/lib/turns/runtime';

export function MessageMeta({
  message,
  modelId,
  chatSettings,
  models,
  showStats,
}: {
  message: Message;
  modelId: string;
  chatSettings: Chat['settings'];
  models: ModelDescriptor[];
  showStats: boolean;
}) {
  const modelInfo = models.find((x) => x.id === modelId);
  let cost: string | undefined;
  let ctxPct: number | undefined;
  if (showStats && message.metrics) {
    const pt = message.metrics.promptTokens ?? message.tokensIn;
    const ct = message.metrics.completionTokens ?? message.tokensOut;
    const { currency, total } = computeCost({
      model: modelInfo,
      promptTokens: pt,
      completionTokens: ct,
      usage: message.usage,
    });
    cost = total && total > 0 ? `${currency} ${total.toFixed(5)}` : undefined;
    const contextLimit = modelInfo?.context_length ?? 8000;
    const reservedForCompletion =
      typeof chatSettings.generation.maxTokens === 'number'
        ? chatSettings.generation.maxTokens
        : 1024;
    const maxPromptTokens = Math.max(512, contextLimit - reservedForCompletion);
    if (pt != null && maxPromptTokens > 0) {
      ctxPct = Math.max(0, Math.min(100, Math.round((pt / maxPromptTokens) * 100)));
    }
  }

  const metricLabels = showStats && message.metrics ? formatMetricsForDisplay(message.metrics) : [];

  return (
    <>
      Generated by <span className="badge">{modelId}</span>
      {showStats && message.metrics && (
        <>
          {metricLabels.map((label) => (
            <span key={label}> · {label}</span>
          ))}
          {ctxPct != null && <span title="Context window fullness"> · ctx {ctxPct}%</span>}
          {cost && <span> · {cost}</span>}
        </>
      )}
    </>
  );
}
